# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: tenAfric

on:
  push:
    branches:
      - main
      - kibet
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Set Git config
      run: |
          git config --local user.email "dennisrkibet@gmail.com"
          git config --local user.name "DennisRono"
    - name: Merge kibet to main
      run: |
          git checkout main
          git merge kibet -m "Auto-merge kibet into main branch"
